version: '2'
services:
    teamspeak3:
        build: .
        ports:
          - "9987:9987/udp"
          - "30033:30033"
          - "10011:10011"
        volumes:
          - /mnt/teamspeak:/data:Z
        restart: always
